<?php

$output           = new stdClass;

$output->elements = $model->find()->toArray();
$output->limit    = $model->getLimit();
$output->offset   = $model->getOffset();
$output->page     = $model->getPage();
$output->count    = count($output->elements);
$output->total    = isset($model->total) ? $model->total : ( ($output->count < $output->limit) ? $output->count : $model->count());

$output->pages    = $output->limit === null ? 1 : ceil($output->total / $output->limit);
$output->start    = $output->count > 0 ? $output->offset + 1 : 0;
$output->end      = $output->count > 0 ? $output->offset + $output->count : 0;

dump($output);