<?php
use Phidias\Core\Layout;
use Phidias\Core\Language;
?>

<?php Layout::block('css'); ?>
    <link rel="stylesheet" type="text/css" media="all" href="<?=$this->URL()?>/DataTables/css/phidias.css" />
<?php Layout::endBlock('css'); ?>

<?php Layout::block('js'); ?>
    <script src="<?=$this->URL()?>/DataTables/js/jquery.dataTables.min.js"></script>
    <script>
    $(function() {

        var aoColumns = new Array;
        $('#example thead th').each( function () {
            if ( $(this).attr('bSortable') == 'false' ) {
                aoColumns.push({"bSortable": false});
            } else {
                aoColumns.push(null);
            }
        } );

        $('#example').dataTable({
            "aoColumns": aoColumns,
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?=$dataTable->getAjaxSource()?>",
            "iDeferLoading": "<?=$dataTable->getTotalRecords()?>",

            "oLanguage": {
                "sUrl": "<?=$this->URL()?>/DataTables/language/es.json"
            }
        });
/*
        $('#example').on('click', 'tbody tr', function() {
            alert('boop');
        } );
*/
    });
    </script>
<?php Layout::endBlock('js'); ?>

<?php if (isset($header)): ?>
<h1><?=$header?></h1>
<?php endif; ?>

<script>

</script>

<input type="range" oninput="$('#example').css('font-size', $(this).val()+'em')" min="0.3" max="1.5" step="0.1" />

<table cellpadding="0" cellspacing="0" border="0" class="display" id="example" width="100%">
    <thead>
        <tr>
            <?php foreach ($dataTable->getColumns() as $column):
                ?>
                <th <?=$column->isSortable ? '' : ' bSortable="false"'?>><?= Language::get($column->title) ?></th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php $odd = FALSE; ?>
        <?php foreach ($dataTable->getData() as $record): ?>
            <?php $odd = !$odd ?>
            <tr class="<?=$odd ? 'odd' : 'even'?>">
                <?php foreach ($dataTable->getColumns() as $column): ?>
                    <td><?= $column->getValue($record) ?></td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>