<?php

use Phidias\Component\Navigation;
?>

<h1>Application</h1>
<a href="<?=Navigation::link()?>">Home</a>

<h2>Que podr&iacute;a ir ac&aacute;...</h2>
<ol>
    <li>aplicacion onLine/offLine</li>
    <li>administrar diccionarios</li>
    <li>
        <span>administrar configuracion</span>
        <ol>
            <li>Fecha y hora</li>
            <li>internacionalizaci&oacute;n</li>
        </ol>
    </li>
    <li>Editor de diccionarios</li>
    <li>Editor de plantillas</li>
</ol>


<pre class="code">
2 languages
7 configuration files

234 resources
134 views
3 layouts

7868 files
123,000 lines of code
</pre>